### ISSUE TITLE
Skeleton problem in level 3

### ISSUE THREAD

**Issue by TinchoteSK** [oklemenz/PrinceJS#9]
In level 3, when fighting the second skeleton, I push it back towards the breaking tile. The tile breaks, but the skeleton doesn't fall. I couldn't replicate, but it did happen at least once.

**Comment by oklemenz** [comment]
I did a fix. So this should not occur anymore.

**Comment by TinchoteSK** [comment]
Thanks for the quick response! And congrats on the recreation of the game,
it's amazing. Is there any documentation on how you recreated everything on
javascript? I'm impressed.

Cheers,


Martin

**Comment by oklemenz** [comment]
Nice that you like it. Thanks for the kind words. The implementation was started already 7 years ago by Ultrabolido, laying the foundation. I found it unfinished missing major parts of the gameplay and a lot of bugs and I decided to complete it and add additional features, like mobile and custom level support.

**Comment by TinchoteSK** [comment]
I'm really impressed, because it really feels like the original. There is
maybe a very tiny different feel in some responses to key presses, but it
is really minimal. It is like playing the original, which sent me scouring
the code a bit because I'm still amazed that it can be replicated that
closely in javascript.

I have many questions and I'll try not to bother you with many, but the
main question I have is how you replicated the levels? Did you have data
from the original binary, or were they replicated visually?

Cheers,


Martin

**Comment by oklemenz** [comment]
Yes, trying to make it feel like the original was one of the goals.  This could be achieved by trying to reuse parts of the original. The level data and the assets were exported from original binaries. There's a community tool to do that: https://www.popot.org/other_useful_tools.php?tool=PR

In addition to that, also the sprite animations have been reverse engineered from the original to have the same look and feel. 

The game logic was recreated in JavaScript manually to match the original as close as possible. 

The code is written, so that's easy to see what's going on.

And Phaser is a great game engine, taking care of rendering all that in the browser.

**Comment by oklemenz** [comment]
Level designs were exported using the great community tool and level editor apoplexy 
https://www.popot.org/level_editors.php?editor=apoplexy

**Comment by TinchoteSK** [comment]
That's amazing, thanks a lot for all of the details!
